language: python

matrix:
  include:
    - python: "2.7"
    - python: "3.5"

before_script:
  - python setup.py develop
  - pip install pytest
  - pip install coveralls

script:
  - coverage run -m py.test tests/TestMethods.py || exit 1

after_success:
  - coveralls

notifications:
  email:
    - pkelley@netflix.com
    - opticrealm@gmail.com
